# not valid file

apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: mongoexpress-ingress
  namespace: mongo
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
  - host: mongoexpress.dynstream.pl # valid domain name
    http:
      paths:
      - backend:
          service:
            name: mongoexpress-service
            port:
              number: 8081