apiVersion: apps/v1
kind: Deployment
# metadata section
metadata:
  name: mongo-express
  labels:
    app: mongoexpress
# specification section
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mongoexpress
  template:
    metadata:
      labels:
        app: mongoexpress
    spec:
      containers:
        - name: mongoexpress
          image: mongo-express:latest
          ports:
            - containerPort: 8081
          env:
            - name: ME_CONFIG_MONGODB_ADMINUSERNAME 
              valueFrom:
                secretKeyRef:
                  name: mongoexpress-secret
                  key: ME_CONFIG_MONGODB_ADMINUSERNAME
            - name: ME_CONFIG_MONGODB_ADMINPASSWORD
              valueFrom:
                secretKeyRef:
                  name: mongoexpress-secret
                  key: ME_CONFIG_MONGODB_ADMINPASSWORD
            - name: ME_CONFIG_MONGODB_SERVER
              valueFrom:
                configMapKeyRef:
                  name: mongodb-configmap
                  key: MONGODB_HOST  