apiVersion: apps/v1
kind: Deployment
# metadata section
metadata:
  name: mongo-express
  labels:
    app: mongoexpress
# specification section
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mongoexpress
  template:
    metadata:
      labels:
        app: mongoexpress
    spec:
      containers:
        - name: mongoexpress
          image: mongo-express:latest
          ports:
            - containerPort: 8081
          env:
            - name: ME_CONFIG_MONGODB_URL
              value: "mongodb://mongoadmin:Mongo%402024Secure@mongodb-service:27017/"
            - name: ME_CONFIG_BASICAUTH_USERNAME
              valueFrom:
                secretKeyRef:
                  name: mongoexpress-secret
                  key: ME_CONFIG_BASICAUTH_USERNAME
            - name: ME_CONFIG_BASICAUTH_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mongoexpress-secret
                  key: ME_CONFIG_BASICAUTH_PASSWORD
            - name: ME_CONFIG_SITE_COOKIESECURE
              value: "false"
            - name: ME_CONFIG_SITE_BASEURL
              value: "/"  